<?php
/**
 * @file
 * Textbook Style Guide
 */
define('TEXTBOOK_RESET_DEFAULT', 1);
define('TEXTBOOK_DEFAULT_SET', 'textbook_core');

/**
 * Implemens hook_menu().
 */
function textbook_menu() {
  $items = array();
  $items['admin/config/content/textbook'] = array(
    'title' => 'Textbook style settings', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('textbook_admin_settings'), 
    'access arguments' => array('administer site configuration'),
    'file' => 'textbook.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_page_alter().
 */
function textbook_page_alter() {
  // include style guide sheets on nodes
  if (arg(0) != 'admin') {
    // apply styles based on the default
    _textbook_apply_style('node');
  }
}

/**
 * Implements hook_html_head_alter().
 */
function textbook_html_head_alter(&$head_elements) {
  $args = arg();
  // account for print module and book print out
  if ($args[0] == 'book' && $args[1] = 'export' && $args[2] == 'html') {
    // book module template ignores css styles added to print
    $locations = _textbook_apply_style('print');
    // parse returned locations array and manually add to html head
    foreach ($locations as $key => $location) {
      $head_elements['textbook_'. $key] = array(
        '#type' => 'html_tag',
        '#tag' => 'link',
        '#attributes' => array(
          'type' => 'text/css',
          'rel' => 'stylesheet',
          'href' => $location,
        ),
      );
    }
  }
  else if ($args[0] == 'print') {
    // print module should respect drupal_add statements
    _textbook_apply_style('print');
  }
}
/**
 * Callback to add in styles.
 */
function _textbook_apply_style($type = 'node') {
  $locations = array();
  // load all styles from hook
  $styles = _textbook_load_styles();
  // load active style
  $active_style = _textbook_active_style();
  // load default style
  $style = $styles[$active_style];
  $api_items = array('css', 'js');
  // include reset if site allows it
  if (variable_get('textbook_reset', TEXTBOOK_RESET_DEFAULT)) {
    $api_items[] = 'reset';
  }
  // loop through defined items
  foreach ($api_items as $item) {
    // verify the item is available
    if (isset($style[$type][$item])) {
      // loop through
      foreach ($style[$type][$item] as $item_location) {
        // assemble all found locations
        $locations[] = $item_location;
        switch ($item) {
          case 'css':
            // add these items as low as possible in page render
            drupal_add_css($item_location, array('group' => CSS_THEME, 'weight' => 100));
          break;
          case 'reset':
            drupal_add_css($item_location);
          break;
          case 'js':
            drupal_add_js($item_location);
          break;
        }
      }
    }
  }
  return $locations;
}

/**
 * Implements hook_textbook_style().
 */
function textbook_textbook_style() {
  // default path for textbookcore
  $tpath = drupal_get_path('module', 'textbook') .'/textbook_styles/textbook_core/';
  $styles = array(
    'textbook_core' => array(
      'name' => t('Textbook core: Default style'),
      'node' => array(
        'css' => array(
          $tpath .'node_tables.css',
          $tpath .'node_lists.css',
          $tpath .'node.css',
        ),
        'reset' => array(
          $tpath .'reset.css',
        ),
      ),
      'print' => array(
        'css' => array(
          $tpath .'print.css',
        ),
      ),
    ),
  );
  return $styles;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function textbook_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implements hook_context_plugins().
 */
function textbook_context_plugins() {
  $plugins = array();
  $plugins['textbook_context_reaction'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'textbook') . '/plugins',
      'file' => 'textbook_context_reaction.inc',
      'class' => 'textbook_context_reaction',
      'parent' => 'context_reaction',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function textbook_context_registry() {
  $registry = array();
  $registry['reactions'] = array(
    'textbook' => array(
      'title' => t('Textbook'),
      'plugin' => 'textbook_context_reaction',
    ),
  );
  return $registry;
}

/**
 * Implements hook_context_page_reaction().
 */
function textbook_context_page_reaction() {
  if ($plugin = context_get_plugin('reaction', 'textbook')) {
    $plugin->execute();
  }
}

/**
 * Implementation of hook_wysiwyg_editor_settings_alter().
 */
function textbook_wysiwyg_editor_settings_alter(&$settings, $context) {
  // settings known to be ok for CKEditor
  if ($context['profile']->editor == 'ckeditor') {
    $settings['undoStackSize'] = 40; // increase the undo history
    $settings['fillEmptyBlocks'] = FALSE;
    $settings['stylesSet'] = _textbook_styles(); // apply our styles
  }
}

/**
 * Helper function to return active textbook style.
 */
function _textbook_active_style() {
  global $active_textbook_style;
  // check for global style to coopt default
  if (isset($active_textbook_style)) {
    $active = $active_textbook_style;
  }
  else {
    $active = variable_get('textbook_active', TEXTBOOK_DEFAULT_SET);
  }
  // developer overide to allow hijacking of active
  drupal_alter('textbook_active_style', $active);
  return $active;
}

/**
 * Helper to load list of all styles.
 */
function _textbook_load_styles() {
  // hook in all styles
  $styles = module_invoke_all('textbook_style');
  // allow other projects to modify established styles
  drupal_alter('textbook_style', $styles);
  return $styles;
}

/**
 * Helper function for defining styles
 */
function _textbook_styles() {
  $styles = array(
    array(
      'name' => 'DIV Center',
      'element' => 'div',
      'attributes' => array(
        'class' => 'textbook_center'
      ),
    ),
    array(
      'name' => 'DIV Right',
      'element' => 'div',
      'attributes' => array(
        'class' => 'textbook_right'
      ),
    ),
    array(
      'name' => 'Emphasis (italic)',
      'element' => 'em',
    ),
    array(
      'name' => 'Strong (bold)',
      'element' => 'strong',
    ),
    array(
      'name' => 'Superscript',
      'element' => 'sup',
    ),
    array(
      'name' => 'Subscript',
      'element' => 'sub',
    ),
    array(
      'name' => 'Color 1',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color1',
      )
    ),
    array(
      'name' => 'Color 2',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color2',
      )
    ),
    array(
      'name' => 'Color 3',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color3',
      )
    ),
    array(
      'name' => 'Color 4',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color4',
      )
    ),
    array(
      'name' => 'Color 5',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color5',
      )
    ),
    array(
      'name' => 'Color 6',
      'element' => 'span',
      'attributes' => array(
        'class' => 'textbook_color6',
      )
    ),
  );
  return $styles;
}